name: Matthias77
favicon: null
layout_spectrum: 0.5808695247396827
typography_spectrum: 0.8906386913731694
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.12855456862598658
  lightness: 0.8219411948230118
  saturation: 0.43203704454936087
  rhythmicContrast: 0.5845009277109057
purpose: []
